export const appConstants: Record<string, string> = {
  appName: "HOOPROSTER",
  defaultTitle: "Dashboard",
  dashboard: "Dashboard",
  // "team-management": "Team Management",
  "budget-tracking": "Team Management",
  "player-database": "Player Database",
  watchlist: "Watchlist",
  notifications: "Notifications",
  news: "News",
  settings: "Settings",
  profile: "My Profile",
  support: "Support",
  "player-profile": "Player Profile",
};
